version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

pull_requests:
  do_not_increment_build_number: true
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: aprk1rgzZGKGkAOgGog2fSYInLko09y3X
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

install:
  - ps: Install-Product node
  
before_build:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: cd swlSimulator
  - npm install
  
build_script:
  - ps: cd ..
  - ps: dotnet build swlsimNET.sln --configuration Release
  - ps: cd swlSimulator
  - ps: node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod
  - ps: node node_modules/webpack/bin/webpack.js --env.prod
  - ps: dotnet publish --configuration Release
  - ps: mkdir c:\projects\swlsimNET\artifacts
  - ps: '&"c:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" ''-verb:sync'' ''-source:archiveDir="C:\projects\swlsimNET\swlSimulator\bin\Any CPU\Release\netcoreapp2.0"'' ''-dest:package="c:\projects\swlSimulator\artifacts\swlSimulator.zip"'' ''-declareParam:name="IIS Web Application Name",defaultValue="swlSimulator",tags="IisApp"'' ''-declareParam:name="IIS Web Application Name",type="ProviderPath",scope="IisApp",match="^.*swlSimulator$"'' ''-declareParam:name="IIS Web Application Name",type="ProviderPath",scope="setAcl",match="^.*swlSimulator'''
  - ps: cd ..
  
cache:
 - packages -> **\*.csproj
 
artifacts:
- path: artifacts\swlSimulator.zip
  name: swlSimulator
  type: WebDeployPackage
